# -*- coding: utf-8 -*-
"""contextDistillation5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17SrfDiaXqqy3IHW89jqQw4b2Joh5eSnf
"""

import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader, TensorDataset
from transformers import AutoModelForCausalLM, AutoTokenizer, AdamW, BertTokenizer, BertForSequenceClassification, OPTForCausalLM, GPT2Tokenizer, Trainer, TrainingArguments, AutoModelForSequenceClassification
from datasets import load_dataset
from tqdm import tqdm
from datasets import load_dataset
from datasets import Dataset
import matplotlib.pyplot as plt

# Initialize models and tokenizer
model_name = "facebook/opt-125m"
tokenizer = AutoTokenizer.from_pretrained(model_name)
teacher_model = OPTForCausalLM.from_pretrained(model_name)
student_model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# Set device for models
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
teacher_model.to(device)
student_model.to(device)

# Load SST-2 dataset from GLUE
dataset = load_dataset("glue", "sst2")
train_dataset = dataset['train']

# Function to analyze sentiment (teacher model's task)
def analyze_sentiment(sentence):
    prompt = f"Analyze the sentiment of this sentence: '{sentence}'\n"
    inputs = tokenizer.encode(prompt, return_tensors='pt').to(device)
    outputs = teacher_model.generate(inputs, max_length=100, num_return_sequences=1, no_repeat_ngram_size=2)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Function to extract label (answer extractor)
def extractor(analysis):
    analysis_lower = analysis.lower()
    return 1 if any(word in analysis_lower for word in ['good', 'right', 'best']) else 0

# Generate sentiment results
sentiment_results = {}
max_length = 100
for i in range(10):  # You might want to process more sentences
    sentence = train_dataset[i]['sentence']
    analysis = analyze_sentiment(sentence)
    result = extractor(analysis)
    sentiment_results[f"Return 1 if the sentiment of this sentence is good, otherwise return 0, here is the sentence: '{sentence}'"] = result

# Prepare the dataset for training
train_texts = list(sentiment_results.keys())
train_labels = list(sentiment_results.values())

# Tokenization and DataLoader Setup
encoded_inputs = tokenizer(train_texts, padding=True, truncation=True, max_length=max_length, return_tensors="pt")
input_ids = encoded_inputs['input_ids']
attention_masks = encoded_inputs['attention_mask']
labels = torch.tensor(train_labels)
train_data = TensorDataset(input_ids, attention_masks, labels)
train_loader = DataLoader(train_data, batch_size=2, shuffle=True)

# Load the evaluation dataset (you can use a different dataset here)
eval_dataset = dataset['validation']

# Select specific data points for evaluation (you can use all or a subset)
selected_eval_indices = range(20)
selected_eval_dataset = [eval_dataset[i] for i in selected_eval_indices]

# Prepare the dataset for evaluation
eval_texts = [f"Return 1 if the sentiment of this sentence is good, otherwise return 0, here is the sentence: '{example['sentence']}'" for example in selected_eval_dataset]
eval_labels = [example['label'] for example in selected_eval_dataset]

# Tokenization and DataLoader Setup for evaluation
encoded_eval_inputs = tokenizer(eval_texts, padding=True, truncation=True, max_length=max_length, return_tensors="pt")
eval_input_ids = encoded_eval_inputs['input_ids']
eval_attention_masks = encoded_eval_inputs['attention_mask']
eval_labels = torch.tensor(eval_labels)
eval_data = TensorDataset(eval_input_ids, eval_attention_masks, eval_labels)
eval_loader = DataLoader(eval_data, batch_size=2, shuffle=False)  # No need to shuffle for evaluation

# Evaluation Loop
student_model.eval()
eval_losses = []
eval_accuracy = 0
eval_steps = 0

with torch.no_grad():
    for eval_batch in tqdm(eval_loader, desc='Evaluating'):
        eval_batch = tuple(b.to(device) for b in eval_batch)
        b_eval_input_ids, b_eval_input_mask, b_eval_labels = eval_batch

        # Forward pass: compute logits and loss
        eval_outputs = student_model(b_eval_input_ids, attention_mask=b_eval_input_mask, labels=b_eval_labels)
        eval_loss = eval_outputs.loss
        eval_losses.append(eval_loss.item())

        # Calculate accuracy
        logits = eval_outputs.logits
        preds = torch.argmax(logits, dim=1)
        eval_accuracy += torch.sum(preds == b_eval_labels).item()
        eval_steps += len(b_eval_labels)

# Calculate average evaluation loss
avg_eval_loss = sum(eval_losses) / len(eval_loader)
print(f'Average Evaluation Loss: {avg_eval_loss}')

# Calculate accuracy
eval_accuracy /= eval_steps
print(f'Evaluation Accuracy: {eval_accuracy}')

# Optimizer Setup
optimizer = AdamW(student_model.parameters(), lr=5e-5, weight_decay=1e-4)

# Training Loop
student_model.train()
epoch_losses = []
step_losses=[]

for epoch in range(15):
    total_loss = 0
    # Wrap train_loader with tqdm for a progress bar
    for batch in tqdm(train_loader, desc=f'Epoch {epoch+1}'):
        batch = tuple(b.to(device) for b in batch)
        b_input_ids, b_input_mask, b_labels = batch

        # Clear previously calculated gradients
        student_model.zero_grad()

        # Forward pass: compute logits and loss (remove token_type_ids)
        outputs = student_model(b_input_ids, attention_mask=b_input_mask, labels=b_labels)
        loss = outputs.loss
        total_loss += loss.item()
        step_losses.append(loss.item())


        # Backward pass: compute gradient and update parameters
        loss.backward()
        optimizer.step()



    # Calculate average loss over the epoch
    avg_train_loss = total_loss / len(train_loader)
    epoch_losses.append(avg_train_loss)

    print(f'Epoch {epoch + 1}, Average Training Loss: {avg_train_loss}')

plt.plot(epoch_losses, label='Training Loss')
plt.xlabel('epoch_losses')
plt.ylabel('Loss')
plt.title('Training Loss Over epoch_losses')
plt.legend()
plt.show()

# Evaluation Function
def evaluate_model(model, dataloader):
    model.eval()
    total_eval_loss = 0
    predictions, true_labels = [], []

    for batch in tqdm(dataloader, desc='Evaluating'):
        batch = tuple(b.to(device) for b in batch)
        b_input_ids, b_input_mask, b_labels = batch

        # Tell the model not to compute or store gradients
        with torch.no_grad():
            # Forward pass, calculate logit predictions
            outputs = model(b_input_ids, attention_mask=b_input_mask, labels=b_labels)
            loss = outputs.loss
            logits = outputs.logits

        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()

        # Store predictions and true labels
        predictions.extend(logits)
        true_labels.extend(label_ids)

    # Calculate average loss over all batches
    avg_eval_loss = total_eval_loss / len(dataloader)

    return predictions, true_labels, avg_eval_loss

# Evaluation DataLoader Setup
eval_loader = DataLoader(train_data, batch_size=2, shuffle=False)  # You can use a separate dataset for evaluation if needed

# Training Loop
# ... (Previous training loop remains unchanged)

# Evaluation Loop
predictions, true_labels, avg_eval_loss = evaluate_model(student_model, eval_loader)

print(f'Average Evaluation Loss: {avg_eval_loss}')

# Convert logits to predictions
predicted_labels = [1 if logits[1] > logits[0] else 0 for logits in predictions]

# Calculate evaluation metrics (e.g., accuracy)
correct_predictions = sum(p == t for p, t in zip(predicted_labels, true_labels))
accuracy = correct_predictions / len(true_labels)
print(f'Accuracy: {accuracy}')

# Load the evaluation dataset (you can use a different dataset here)
eval_dataset = dataset['validation']

# Select specific data points for evaluation (you can use all or a subset)
selected_eval_indices = range(20)
selected_eval_dataset = [eval_dataset[i] for i in selected_eval_indices]

# Prepare the dataset for evaluation
eval_texts = [f"Return 1 if the sentiment of this sentence is good, otherwise return 0, here is the sentence: '{example['sentence']}'" for example in selected_eval_dataset]
eval_labels = [example['label'] for example in selected_eval_dataset]

# Tokenization and DataLoader Setup for evaluation
encoded_eval_inputs = tokenizer(eval_texts, padding=True, truncation=True, max_length=max_length, return_tensors="pt")
eval_input_ids = encoded_eval_inputs['input_ids']
eval_attention_masks = encoded_eval_inputs['attention_mask']
eval_labels = torch.tensor(eval_labels)
eval_data = TensorDataset(eval_input_ids, eval_attention_masks, eval_labels)
eval_loader = DataLoader(eval_data, batch_size=2, shuffle=False)  # No need to shuffle for evaluation

# Evaluation Loop
student_model.eval()
eval_losses = []
eval_accuracy = 0
eval_steps = 0

with torch.no_grad():
    for eval_batch in tqdm(eval_loader, desc='Evaluating'):
        eval_batch = tuple(b.to(device) for b in eval_batch)
        b_eval_input_ids, b_eval_input_mask, b_eval_labels = eval_batch

        # Forward pass: compute logits and loss
        eval_outputs = student_model(b_eval_input_ids, attention_mask=b_eval_input_mask, labels=b_eval_labels)
        eval_loss = eval_outputs.loss
        eval_losses.append(eval_loss.item())

        # Calculate accuracy
        logits = eval_outputs.logits
        preds = torch.argmax(logits, dim=1)
        eval_accuracy += torch.sum(preds == b_eval_labels).item()
        eval_steps += len(b_eval_labels)

# Calculate average evaluation loss
avg_eval_loss = sum(eval_losses) / len(eval_loader)
print(f'Average Evaluation Loss: {avg_eval_loss}')

# Calculate accuracy
eval_accuracy /= eval_steps
print(f'Evaluation Accuracy: {eval_accuracy}')